spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/inventoryDB
    username: postgres
    password: anderson
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true